-- ============================================================
-- UTecnologia Saúde — Cluster "Chatbot e autoatendimento por WhatsApp"
-- Rodada: 2026-09-23
-- Importar via phpMyAdmin: banco utecnologiacom_db
-- ATENÇÃO: id_categoria = 1 em todos (mesma categoria dos artigos
-- anteriores). Conteúdo descreve só o que já está em produção.
-- ============================================================

INSERT INTO `blog_posts`
  (`id_categoria`, `titulo`, `slug`, `resumo`, `conteudo`, `meta_titulo`, `meta_descricao`, `autor`, `tempo_leitura`, `publicado`, `criado_em`, `publicado_em`)
VALUES
-- ARTIGO 1
(1,
 'Sistema de agendamento com WhatsApp: o que dá para automatizar',
 'sistema-de-agendamento-com-whatsapp-o-que-da-para-automatizar',
 'O que um sistema de agendamento com WhatsApp realmente automatiza numa clínica — confirmação, lembrete, remarcação, cancelamento e agenda do dia — e o que continua com a equipe.',
 '<p>Quem procura um sistema de agendamento com WhatsApp geralmente quer uma coisa: parar de digitar mensagens à mão e reduzir faltas. Mas "integração com WhatsApp" pode significar coisas bem diferentes. Este guia separa o que dá para automatizar de verdade do que continua sendo trabalho da equipe.</p><h2>O que dá para automatizar</h2><ul><li><strong>Confirmação no momento do agendamento:</strong> ao marcar a consulta, o paciente recebe uma mensagem com botões de confirmar ou cancelar.</li><li><strong>Lembrete antes da consulta:</strong> um envio automático poucas horas antes, apenas para quem ainda não confirmou nem cancelou.</li><li><strong>Resposta do paciente na agenda:</strong> ao tocar no botão, o status muda sozinho e a agenda mostra "Confirmado via WhatsApp" ou "Cancelado via WhatsApp".</li><li><strong>Remarcar e cancelar pelo chat:</strong> com 24 horas ou mais de antecedência, o paciente escolhe outro dia e horário livres do mesmo profissional, sem passar pela recepção.</li><li><strong>Agenda do dia para a equipe:</strong> profissional e atendente consultam a agenda de hoje e de amanhã pelo próprio WhatsApp.</li><li><strong>Avisos para quem precisa saber:</strong> quando o paciente confirma ou cancela, a equipe e o profissional recebem um aviso.</li></ul><h2>O que continua com a equipe</h2><ul><li>Conversa livre e dúvidas clínicas: um chatbot de agenda não faz triagem nem responde sobre tratamento.</li><li>Remarcações com menos de 24 horas, ou de profissional sem horários cadastrados: o pedido chega para a equipe decidir.</li><li>Marcar uma consulta nova do zero pelo WhatsApp: hoje o paciente remarca ou cancela uma consulta existente, mas a marcação inicial é feita pela recepção.</li></ul><h2>Requisitos que ninguém conta</h2><p>O envio oficial usa a WhatsApp Cloud API da Meta, com mensagens modelo aprovadas pela própria Meta. Isso exige uma conexão configurada uma vez e um número de telefone cadastrado para cada paciente. Sem número válido, nada é enviado.</p><h2>Como avaliar um sistema</h2><p>Pergunte se a resposta do paciente atualiza a agenda sozinha (e não só chega numa caixa de mensagens), se existe controle por perfil (paciente, profissional, atendente) e se o que a ferramenta promete é o que está em produção. Veja como isso funciona na prática na página de <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">confirmação e chatbot por WhatsApp</a>.</p><h2>Perguntas frequentes</h2><h3>O sistema envia mensagem em massa para pacientes?</h3><p>Não é esse o objetivo. O envio é ligado a eventos da agenda: agendamento, lembrete e resposta do paciente.</p><h3>Preciso trocar meu número de WhatsApp?</h3><p>A conexão usa a API oficial da Meta, configurada com o número da clínica; o processo é feito uma vez na área de administração.</p><p>Quer ver o fluxo completo? <a href="https://utecnologia.com.br/experimentar">teste o sistema por 30 dias</a>.</p>',
 'Sistema de agendamento com WhatsApp: o que dá para automatizar',
 'O que um sistema de agendamento com WhatsApp automatiza na clínica: confirmação, lembrete, remarcar, cancelar e agenda do dia — e o que ainda é da equipe.',
 'UTecnologia Saúde', 7, 1, '2026-09-22 09:00:00', '2026-09-22 09:00:00'),
-- ARTIGO 2
(1,
 'Enviar mensagem para paciente no WhatsApp: cuidados com a LGPD',
 'enviar-mensagem-para-paciente-whatsapp-lgpd',
 'Boas práticas para clínicas que enviam confirmação e lembrete de consulta por WhatsApp respeitando a LGPD: o que colocar na mensagem, o que evitar e como registrar.',
 '<p>Confirmar consulta por WhatsApp é comum, mas dados de saúde são dados sensíveis pela LGPD. Isso não impede o envio; exige cuidado com o que vai na mensagem e com quem a recebe. Este texto reúne boas práticas gerais e não substitui a orientação de um advogado ou do seu encarregado de dados.</p><h2>Coloque o mínimo necessário na mensagem</h2><p>Uma mensagem de confirmação precisa de nome do paciente, data, hora e profissional. Não precisa de diagnóstico, motivo da consulta, exame ou qualquer informação clínica. Quanto menos dado, menor o risco se a mensagem for vista por outra pessoa no aparelho.</p><h2>Use o canal oficial</h2><p>A WhatsApp Cloud API da Meta permite enviar mensagens modelo aprovadas, com registro de entrega. Ferramentas que usam número pessoal ou automação não oficial expõem a clínica a bloqueios e dificultam comprovar o que foi enviado.</p><h2>Base legal e transparência</h2><p>O contato para confirmar uma consulta já marcada costuma se apoiar na execução do serviço contratado pelo paciente. Ainda assim, vale informar no cadastro que a clínica usa WhatsApp para confirmações e lembretes, e dar uma forma simples de o paciente pedir para não receber.</p><h2>Confira o número antes de enviar</h2><p>Erro de digitação é o risco mais comum: a confirmação vai para a pessoa errada. Um sistema que só envia para o telefone cadastrado no paciente, e não aceita conversa livre, reduz esse problema.</p><h2>Controle de acesso por perfil</h2><p>Quem consulta a agenda pelo WhatsApp deve ver só o que o seu perfil permite. No UTecnologia Saúde, o chatbot identifica o telefone cadastrado e libera opções por perfil (paciente, profissional, atendente, administrador); um número ligado a mais de um usuário é recusado por segurança.</p><h2>Registre o que foi enviado</h2><p>Guarde quando a mensagem foi enviada, para quem e qual foi a resposta. Isso ajuda a demonstrar conformidade e a resolver reclamações. Veja também nosso artigo sobre <a href="https://utecnologia.com.br/blog/lgpd-para-clinicas-o-que-muda">LGPD para clínicas</a> e a página de <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">confirmação e chatbot por WhatsApp</a>.</p><h2>Perguntas frequentes</h2><h3>Posso mandar o resultado de exame por WhatsApp?</h3><p>É uma decisão de risco alto: resultado é dado sensível. O ideal é avisar que está disponível e entregar por canal com controle de acesso.</p><h3>Preciso de consentimento para lembrar a consulta?</h3><p>Depende do caso e da sua base legal; consulte seu encarregado de dados. Em qualquer cenário, ofereça uma forma clara de o paciente não receber as mensagens.</p><p><a href="https://utecnologia.com.br/experimentar">teste o sistema por 30 dias</a> e veja como o envio é registrado.</p>',
 'Enviar mensagem para paciente no WhatsApp: cuidados com a LGPD',
 'Boas práticas de LGPD para clínicas que enviam confirmação e lembrete de consulta por WhatsApp: conteúdo da mensagem, base legal, opt-out e registro.',
 'UTecnologia Saúde', 6, 1, '2026-09-22 10:00:00', '2026-09-22 10:00:00'),
-- ARTIGO 3
(1,
 'Paciente pode remarcar consulta pelo WhatsApp? Como funciona',
 'paciente-remarcar-consulta-pelo-whatsapp',
 'Como funciona a remarcação e o cancelamento de consulta pelo WhatsApp: regra de 24 horas, escolha de dia e horário livres, avisos à equipe e o que acontece fora da regra.',
 '<p>Sim, o paciente pode remarcar ou cancelar a consulta pelo WhatsApp, sem ligar para a clínica, desde que o sistema tenha os horários do profissional cadastrados. Veja o passo a passo no UTecnologia Saúde.</p><h2>Como o paciente remarca</h2><ol><li>Ele envia uma mensagem e abre o menu do chatbot com o telefone cadastrado.</li><li>Escolhe "Remarcar" e a consulta que quer mudar.</li><li>O chatbot lista os dias com vaga do mesmo profissional, em até 30 dias.</li><li>Ele escolhe o dia, depois o horário, e confirma.</li><li>A agenda é atualizada na hora e o paciente recebe a confirmação.</li></ol><h2>Como o paciente cancela</h2><p>O caminho é parecido: escolher "Cancelar", a consulta, informar um motivo (ou tocar em "Prefiro não informar") e confirmar. O horário volta a ficar livre para outro paciente.</p><h2>A regra das 24 horas</h2><p>A remarcação e o cancelamento automáticos valem quando faltam 24 horas ou mais para a consulta, e o novo horário também precisa estar a 24 horas ou mais. Isso protege a agenda do profissional contra mudanças de última hora.</p><h2>E quando não se encaixa na regra?</h2><p>Se falta menos de 24 horas, se o profissional não tem horários cadastrados ou se não há vaga nos próximos 30 dias, o chatbot pede o motivo e envia um pedido para a equipe, que decide no sistema.</p><h2>O que a equipe vê</h2><p>Quem marcou a consulta e o profissional recebem um aviso no sistema (o sino de notificações). O cancelamento automático também avisa por WhatsApp. A agenda exibe a etiqueta "Confirmado via WhatsApp" ou "Cancelado via WhatsApp".</p><h2>Perguntas frequentes</h2><h3>O paciente pode trocar de profissional?</h3><p>Não. A remarcação automática é sempre com o mesmo profissional.</p><h3>Dois pacientes podem pegar o mesmo horário?</h3><p>Não. O sistema confere a vaga no momento de gravar; se alguém pegou o horário antes, o paciente escolhe outro.</p><p>Conheça a página de <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">confirmação e chatbot por WhatsApp</a> ou <a href="https://utecnologia.com.br/experimentar">teste o sistema por 30 dias</a>. Para reduzir faltas, veja também <a href="https://utecnologia.com.br/blog/como-reduzir-faltas-de-pacientes-no-consultorio">como reduzir faltas de pacientes</a>.</p>',
 'Paciente pode remarcar consulta pelo WhatsApp? Como funciona',
 'Como o paciente remarca ou cancela a consulta pelo chatbot do WhatsApp: regra de 24 horas, horários livres do profissional e avisos à equipe.',
 'UTecnologia Saúde', 6, 1, '2026-09-22 11:00:00', '2026-09-22 11:00:00'),
-- ARTIGO 4
(1,
 'Agenda do dia pelo WhatsApp: como médicos e recepção consultam',
 'agenda-do-dia-pelo-whatsapp-para-medicos-e-clinicas',
 'Como o profissional e a recepção consultam a agenda de hoje e de amanhã pelo WhatsApp, sem abrir o sistema, e quais opções cada perfil enxerga.',
 '<p>Entre um atendimento e outro, abrir o sistema no computador nem sempre é prático. No UTecnologia Saúde, o profissional e a recepção consultam a agenda pelo WhatsApp, com as opções liberadas para o seu perfil.</p><h2>O que cada perfil consulta</h2><ul><li><strong>Profissional:</strong> agenda de hoje, agenda de amanhã, pendências, plano e suporte.</li><li><strong>Atendente (recepção):</strong> agenda de hoje, agenda de amanhã, pendências e suporte.</li><li><strong>Administrador:</strong> agenda, pendências, cancelamentos, plano e suporte.</li><li><strong>Paciente:</strong> próximas consultas, remarcar e cancelar.</li></ul><h2>Como funciona</h2><p>A pessoa envia uma mensagem para o número da clínica. O sistema identifica o telefone cadastrado, reconhece o perfil e mostra o menu. Ao escolher "Agenda de hoje", recebe a lista dos horários do dia, com o nome do paciente e o status de cada consulta (pendente, confirmado ou cancelado).</p><h2>Pendências e cancelamentos</h2><p>"Pendências" mostra as consultas que ainda não foram confirmadas, útil para a recepção priorizar contatos. "Cancelamentos" (para o administrador) lista o que o paciente cancelou, inclusive pelo chatbot.</p><h2>Segurança</h2><p>Só números cadastrados recebem opções. Cada perfil enxerga apenas o que o seu nível permite, e um telefone ligado a mais de um usuário é recusado. Leia mais sobre cuidados com dados no artigo sobre <a href="https://utecnologia.com.br/blog/enviar-mensagem-para-paciente-whatsapp-lgpd">mensagens a pacientes e LGPD</a>.</p><h2>Perguntas frequentes</h2><h3>Preciso instalar algum aplicativo?</h3><p>Não. Basta o WhatsApp e o telefone cadastrado no sistema.</p><h3>Dá para editar a agenda pelo WhatsApp?</h3><p>Não. O profissional e a recepção consultam; alterações continuam sendo feitas no sistema.</p><p>Veja a página de <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">confirmação e chatbot por WhatsApp</a> ou <a href="https://utecnologia.com.br/experimentar">teste o sistema por 30 dias</a>.</p>',
 'Agenda do dia pelo WhatsApp: como médicos e recepção consultam',
 'Como médicos e recepção consultam a agenda de hoje e de amanhã pelo WhatsApp, com opções diferentes por perfil e sem abrir o sistema.',
 'UTecnologia Saúde', 5, 1, '2026-09-22 12:00:00', '2026-09-22 12:00:00'),
-- ARTIGO 5
(1,
 'Chatbot para clínica no WhatsApp: o que faz e o que não faz',
 'chatbot-para-clinica-whatsapp-o-que-faz-e-o-que-nao-faz',
 'O que um chatbot de WhatsApp para clínicas faz de verdade — agenda, remarcação, cancelamento, confirmação — e o que não faz, como triagem e conversa livre.',
 '<p>"Chatbot para clínica" pode ser desde um menu simples até uma inteligência artificial que conversa livremente. Para agenda, o menu simples costuma resolver mais e com menos risco. Veja o que o chatbot do UTecnologia Saúde faz e não faz.</p><h2>O que ele faz</h2><ul><li>Mostra um menu de opções de acordo com o perfil do telefone cadastrado.</li><li>Para o paciente: lista as próximas consultas, remarca e cancela (automático com 24 horas ou mais de antecedência).</li><li>Para profissional e recepção: agenda de hoje, de amanhã e pendências.</li><li>Recebe as respostas de confirmação e cancelamento por botão e atualiza a agenda.</li><li>Avisa a equipe e o profissional quando o paciente remarca ou cancela.</li></ul><h2>O que ele não faz</h2><ul><li><strong>Não faz triagem</strong> nem orienta sobre sintomas ou tratamentos.</li><li><strong>Não conduz conversa livre:</strong> ele segue um menu e responde dentro das opções.</li><li><strong>Não marca uma consulta nova</strong> do zero: hoje o paciente remarca ou cancela uma existente.</li><li><strong>Não substitui a recepção:</strong> casos fora das regras vão para a equipe.</li></ul><h2>Por que menu e não conversa livre</h2><p>Em saúde, respostas inventadas são um risco. Um fluxo fechado é previsível, fácil de auditar e não promete o que a clínica não pode cumprir.</p><h2>Requisitos</h2><p>O telefone precisa estar cadastrado no sistema, o envio usa a API oficial do WhatsApp da Meta e a remarcação automática precisa dos horários de atendimento do profissional configurados.</p><h2>Perguntas frequentes</h2><h3>O chatbot funciona 24 horas?</h3><p>Sim, o menu responde a qualquer hora; o que precisa de análise humana fica registrado para a equipe.</p><h3>Ele atende quem não é paciente cadastrado?</h3><p>Não. Números não cadastrados recebem apenas uma orientação para entrar em contato.</p><p>Conheça a página de <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">confirmação e chatbot por WhatsApp</a>, leia <a href="https://utecnologia.com.br/blog/paciente-remarcar-consulta-pelo-whatsapp">como o paciente remarca pelo WhatsApp</a> ou <a href="https://utecnologia.com.br/experimentar">teste o sistema por 30 dias</a>.</p>',
 'Chatbot para clínica no WhatsApp: o que faz e o que não faz',
 'O que um chatbot de WhatsApp para clínicas faz (agenda, remarcar, cancelar, confirmar) e o que não faz (triagem, conversa livre, diagnóstico).',
 'UTecnologia Saúde', 6, 1, '2026-09-22 13:00:00', '2026-09-22 13:00:00');
