-- ============================================================
-- UTecnologia Saúde — Cluster "Confirmação/Lembrete por WhatsApp"
-- Rodada: 2026-08-31
-- Importar via phpMyAdmin: banco utecnologiacom_db
-- ATENÇÃO: id_categoria = 1 em todos (mesma categoria de
-- "Gestão de clínica médica" em docs/blog-posts-seed.sql).
-- Confira/ajuste o id antes de rodar, se necessário.
-- GATE: só publicar (aplicar este SQL + sitemaps + menu) quando
-- o cron de lembrete automático estiver no ar.
-- ============================================================

INSERT INTO `blog_posts`
  (`id_categoria`, `titulo`, `slug`, `resumo`, `conteudo`, `meta_titulo`, `meta_descricao`, `autor`, `tempo_leitura`, `publicado`, `criado_em`, `publicado_em`)
VALUES
-- ARTIGO 1
(1,
 'Modelos de mensagem de confirmação de consulta para WhatsApp',
 'modelo-de-mensagem-de-confirmacao-de-consulta-whatsapp',
 'Textos prontos para confirmar consultas pelo WhatsApp, por tipo de atendimento, com boas práticas de horário e tom — e como automatizar o envio.',
 '<p>Confirmar a consulta pelo WhatsApp reduz falta e retrabalho, mas a mensagem precisa ser curta, clara e fácil de responder. Abaixo estão modelos prontos para copiar e adaptar ao nome da sua clínica.</p><h2>Modelo para consulta médica</h2><p>Olá, [nome do paciente]! Sua consulta com [profissional] está marcada para [dia] às [hora], na [clínica]. Podemos confirmar? Responda <strong>SIM</strong> para confirmar ou <strong>NÃO</strong> para remarcar.</p><h2>Modelo para retorno</h2><p>Oi, [nome]! Passando para confirmar seu retorno com [profissional] em [dia], às [hora]. Se precisar remarcar, é só responder esta mensagem.</p><h2>Modelo para primeira consulta</h2><p>Olá, [nome]! Sua primeira consulta na [clínica] está agendada para [dia] às [hora]. Chegue 10 minutos antes e traga documento e carteirinha do convênio, se tiver. Podemos confirmar?</p><h2>Modelo para exame</h2><p>Oi, [nome]! Seu exame de [tipo] está marcado para [dia] às [hora]. Preparo: [instrução]. Confirma a presença?</p><h2>Boas práticas</h2><ul><li>Envie a confirmação com 24 a 48 horas de antecedência.</li><li>Use o primeiro nome do paciente e o nome do profissional.</li><li>Ofereça sempre uma forma simples de responder (SIM/NÃO ou botões).</li><li>Evite enviar em horário noturno.</li><li>Não coloque diagnóstico nem detalhe clínico na mensagem.</li></ul><h2>Como automatizar isso</h2><p>Digitar mensagem por mensagem consome o tempo da recepção. No <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">sistema de confirmação de consulta por WhatsApp</a> da UTecnologia Saúde, a mensagem sai sozinha quando a consulta é agendada, com botões de confirmar e cancelar, e a resposta do paciente atualiza a agenda automaticamente. Veja também <a href="https://utecnologia.com.br/blog/mensagem-de-lembrete-de-consulta-quando-enviar">quando enviar o lembrete</a>. Para testar na sua clínica, <a href="https://utecnologia.com.br/experimentar">crie uma conta grátis por 30 dias</a>.</p>',
 'Modelos de mensagem de confirmação de consulta para WhatsApp',
 'Textos prontos para confirmar consultas pelo WhatsApp por tipo de atendimento, com boas práticas de horário e tom, e como automatizar o envio.',
 'UTecnologia Saúde', 6, 1, '2026-08-31 09:00:00', '2026-08-31 09:00:00'),
-- ARTIGO 2
(1,
 'Mensagem de lembrete de consulta: modelos e quando enviar',
 'mensagem-de-lembrete-de-consulta-quando-enviar',
 'Qual a diferença entre lembrete e confirmação, as melhores janelas para enviar (véspera e manhã do dia) e modelos prontos para WhatsApp.',
 '<p>O lembrete de consulta serve para trazer o paciente de volta à memória perto da data. É diferente da confirmação, que pede uma resposta. Muitas clínicas usam os dois: confirmam no agendamento e lembram na véspera.</p><h2>Lembrete ou confirmação?</h2><p><strong>Confirmação:</strong> pede que o paciente responda (SIM/NÃO ou botão). Serve para liberar o horário se ele não puder vir.</p><p><strong>Lembrete:</strong> só avisa. Não exige resposta, mas pode oferecer a opção de cancelar.</p><h2>Quando enviar o lembrete</h2><ul><li><strong>24 horas antes (véspera):</strong> janela principal. Tempo suficiente para o paciente se organizar ou avisar que não vem.</li><li><strong>Na manhã do dia:</strong> segundo toque para consultas da tarde. Reduz a falta de quem esqueceu.</li><li>Evite lembrar com mais de 3 dias de antecedência: o paciente esquece de novo.</li></ul><h2>Modelo de lembrete simples</h2><p>Oi, [nome]! Lembrete da sua consulta com [profissional] amanhã, [dia], às [hora], na [clínica]. Se não puder vir, avise por aqui para liberarmos o horário.</p><h2>Modelo de lembrete no dia</h2><p>Bom dia, [nome]! Sua consulta é hoje às [hora], na [clínica]. Até logo!</p><h2>Erros comuns</h2><ul><li>Enviar cedo demais e não repetir perto da data.</li><li>Lembrete sem dizer o profissional e o endereço.</li><li>Não dar opção de cancelar — o paciente que não pode vir simplesmente falta.</li></ul><h2>Fazendo isso sem trabalho manual</h2><p>No <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">recurso de confirmação e lembrete por WhatsApp</a> da UTecnologia Saúde, um processo roda de hora em hora e dispara o lembrete nas janelas que você definir. O paciente confirma ou cancela pelo botão e a agenda se atualiza. Veja também os <a href="https://utecnologia.com.br/blog/modelo-de-mensagem-de-confirmacao-de-consulta-whatsapp">modelos de mensagem de confirmação</a> e <a href="https://utecnologia.com.br/experimentar">teste grátis por 30 dias</a>.</p>',
 'Mensagem de lembrete de consulta: modelos e quando enviar',
 'Diferença entre lembrete e confirmação, as melhores janelas de envio pelo WhatsApp e modelos prontos para reduzir faltas na clínica.',
 'UTecnologia Saúde', 6, 1, '2026-08-31 09:10:00', '2026-08-31 09:10:00'),
-- ARTIGO 3
(1,
 'Como montar a mensagem de confirmação de consulta no WhatsApp: passo a passo',
 'como-fazer-mensagem-de-confirmacao-de-consulta-no-whatsapp',
 'O que não pode faltar na mensagem, o tom certo, como oferecer a resposta sim/não e o que muda ao usar o WhatsApp Business API com modelo aprovado.',
 '<p>Uma boa mensagem de confirmação tem que ser lida e respondida em segundos. Este passo a passo mostra como montar a sua.</p><h2>1. Comece pelo nome</h2><p>Use o primeiro nome do paciente. Mensagem que começa com "Prezado(a) senhor(a)" parece cobrança e é ignorada.</p><h2>2. Diga o essencial em uma linha</h2><p>Profissional, dia, hora e local. Nada além disso no primeiro parágrafo.</p><h2>3. Peça a confirmação de forma objetiva</h2><p>"Podemos confirmar? Responda SIM ou NÃO." Se usar botões, melhor ainda: o paciente responde com um toque.</p><h2>4. Ajuste o tom à clínica</h2><p>Consultório de psicologia costuma usar tom mais acolhedor; clínica de exames, tom mais direto. Mantenha o mesmo padrão em todas as mensagens.</p><h2>5. Não coloque dado clínico</h2><p>Nada de diagnóstico, resultado ou motivo da consulta. Isso é dado sensível e não deve trafegar por mensagem.</p><h2>6. Defina o horário de envio</h2><p>Entre 8h e 20h, 24 a 48 horas antes. Envio de madrugada gera bloqueio e reclamação.</p><h2>O que muda com o WhatsApp Business API</h2><p>Para enviar em escala sem risco de bloqueio, a clínica usa a WhatsApp Cloud API (versão oficial da Meta) com um <strong>modelo de mensagem aprovado</strong>. O texto livre fica limitado; a estrutura da confirmação segue o modelo homologado, com botões padronizados.</p><h2>Ou deixe o sistema fazer</h2><p>O <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">recurso de confirmação por WhatsApp</a> da UTecnologia Saúde já vem com o modelo aprovado e os botões de confirmar/cancelar. A mensagem sai quando a consulta é agendada e a resposta atualiza a agenda. <a href="https://utecnologia.com.br/experimentar">Crie uma conta grátis</a> para ver o fluxo.</p>',
 'Como montar a mensagem de confirmação de consulta no WhatsApp',
 'Passo a passo para escrever a mensagem de confirmação de consulta: o que incluir, o tom certo, horário de envio e o que muda com o WhatsApp Business API.',
 'UTecnologia Saúde', 6, 1, '2026-08-31 09:20:00', '2026-08-31 09:20:00'),
-- ARTIGO 4
(1,
 'Confirmação de consulta: manual pelo WhatsApp ou automática?',
 'confirmacao-de-consulta-manual-ou-automatica',
 'O custo real de confirmar consulta na mão, quando o volume de agendamentos justifica automatizar e o que muda com a resposta do paciente caindo direto na agenda.',
 '<p>Toda clínica confirma consulta de algum jeito. A pergunta é se vale a pena continuar fazendo isso na mão.</p><h2>O custo do processo manual</h2><ul><li>Tempo da recepção: alguns minutos por paciente, todo dia, multiplicado pela agenda inteira.</li><li>Esquecimento: em dia cheio, parte das confirmações não é enviada.</li><li>Controle solto: as respostas ficam no celular de uma pessoa, não na agenda.</li><li>Falta sem aviso: sem confirmação ativa, o horário vago só aparece quando o paciente não chega.</li></ul><h2>Quando o volume justifica automatizar</h2><p>Se a clínica passa de 15 a 20 agendamentos por dia, ou tem mais de um profissional, o processo manual começa a falhar. A partir daí, automatizar paga o próprio custo em agenda aproveitada.</p><h2>O que muda com a confirmação automática</h2><p>A mensagem sai sozinha no agendamento e o lembrete roda de hora em hora. O paciente confirma ou cancela pelo botão e o <strong>status do agendamento muda sem ninguém digitar</strong>. Cancelou? O horário fica livre para a recepção remarcar.</p><h2>O que ainda é decisão da clínica</h2><p>Reagendar continua sendo feito pela recepção — o paciente confirma ou cancela, mas não escolhe outro horário sozinho. E conversas fora do modelo aprovado não fazem parte do recurso.</p><h2>Testando na prática</h2><p>O <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">sistema de confirmação por WhatsApp</a> da UTecnologia Saúde faz esse fluxo de ponta a ponta. Veja também <a href="https://utecnologia.com.br/blog/como-reduzir-faltas-de-pacientes-no-consultorio">como reduzir faltas de pacientes</a> e <a href="https://utecnologia.com.br/blog/modelo-de-mensagem-de-confirmacao-de-consulta-whatsapp">modelos de mensagem</a>. Para experimentar, <a href="https://utecnologia.com.br/experimentar">crie uma conta grátis por 30 dias</a>.</p>',
 'Confirmação de consulta: manual pelo WhatsApp ou automática?',
 'Compare o custo de confirmar consulta na mão com a confirmação automática por WhatsApp e veja quando o volume de agendamentos justifica automatizar.',
 'UTecnologia Saúde', 6, 1, '2026-08-31 09:30:00', '2026-08-31 09:30:00'),
-- ARTIGO 5
(1,
 'Como reduzir faltas de pacientes no consultório',
 'como-reduzir-faltas-de-pacientes-no-consultorio',
 'Sete práticas para diminuir o no-show na clínica: confirmação ativa, lembrete na véspera, política de remarcação, lista de espera e agenda realista.',
 '<p>Falta de paciente é buraco na agenda e prejuízo direto. Não existe solução única, mas um conjunto de práticas simples derruba bastante o índice de no-show.</p><h2>1. Confirmação ativa</h2><p>Não basta lembrar: peça uma resposta. Quem não pode vir avisa e o horário é liberado.</p><h2>2. Lembrete na véspera e no dia</h2><p>Um toque 24 horas antes e outro na manhã das consultas da tarde. Simples e eficaz.</p><h2>3. Facilite o cancelamento</h2><p>Se cancelar dá trabalho, o paciente prefere sumir. Um botão de cancelar na mensagem resolve.</p><h2>4. Política de remarcação clara</h2><p>Deixe explícito como remarcar e em quanto tempo de antecedência. Combine isso já na primeira consulta.</p><h2>5. Lista de espera</h2><p>Tenha pacientes dispostos a antecipar. Quando abre um horário, você preenche no mesmo dia.</p><h2>6. Agenda realista</h2><p>Overbooking gera atraso, atraso gera insatisfação e insatisfação gera falta na próxima. Ajuste o tempo médio de consulta ao que acontece de verdade.</p><h2>7. Acompanhe o número</h2><p>Meça a taxa de falta por profissional e por período. Sem número, não dá para saber se as ações funcionam.</p><h2>Automatizando os passos 1 a 3</h2><p>O <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">recurso de confirmação e lembrete por WhatsApp</a> da UTecnologia Saúde cobre confirmação ativa, lembrete automático e cancelamento por botão, com baixa direta na agenda. Veja também <a href="https://utecnologia.com.br/blog/o-que-fazer-quando-paciente-nao-confirma-consulta">o que fazer quando o paciente não confirma</a>. <a href="https://utecnologia.com.br/experimentar">Teste grátis por 30 dias</a>.</p>',
 'Como reduzir faltas de pacientes no consultório: 7 práticas',
 'Sete práticas para diminuir o no-show: confirmação ativa, lembrete por WhatsApp, cancelamento fácil, lista de espera e agenda realista.',
 'UTecnologia Saúde', 6, 1, '2026-08-31 09:40:00', '2026-08-31 09:40:00'),
-- ARTIGO 6
(1,
 'O que fazer quando o paciente não confirma a consulta',
 'o-que-fazer-quando-paciente-nao-confirma-consulta',
 'Um fluxo prático para o horário parado: prazo-limite de confirmação, mensagem de cobrança, quando liberar a vaga e como usar a lista de espera.',
 '<p>O paciente recebeu a mensagem e não respondeu. Segurar o horário às cegas é perder agenda; cancelar cedo demais é arriscar o paciente aparecer. O caminho é ter um fluxo.</p><h2>1. Defina um prazo-limite</h2><p>Exemplo: confirmação até 18h do dia anterior. O paciente sabe a regra desde o agendamento.</p><h2>2. Envie uma segunda mensagem</h2><p>Perto do prazo, um toque final: "Ainda não recebemos sua confirmação para [dia] às [hora]. Podemos manter o horário?"</p><h2>3. Sem resposta até o prazo, acione a lista de espera</h2><p>Ofereça a vaga para quem quer antecipar. Se alguém aceita, o horário não fica ocioso.</p><h2>4. Libere ou mantenha com critério</h2><p>Paciente recorrente e pontual: vale manter mesmo sem confirmar. Primeira consulta sem confirmação: prioridade para a lista de espera.</p><h2>5. Registre o padrão</h2><p>Quem falta sem avisar com frequência entra num acompanhamento à parte — confirmação reforçada ou cobrança de taxa, conforme a política da clínica.</p><h2>Como o sistema ajuda</h2><p>No <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">recurso de confirmação por WhatsApp</a> da UTecnologia Saúde, o agendamento sem resposta fica visível na agenda como não confirmado, e o cancelamento pelo botão libera a vaga na hora. Veja também <a href="https://utecnologia.com.br/blog/como-reduzir-faltas-de-pacientes-no-consultorio">as 7 práticas para reduzir faltas</a>. <a href="https://utecnologia.com.br/experimentar">Crie uma conta grátis</a>.</p>',
 'O que fazer quando o paciente não confirma a consulta',
 'Fluxo prático para o horário sem confirmação: prazo-limite, mensagem de cobrança, lista de espera e quando liberar a vaga.',
 'UTecnologia Saúde', 5, 1, '2026-08-31 09:50:00', '2026-08-31 09:50:00'),
-- ARTIGO 7
(1,
 'Mensagem de confirmação de consulta odontológica: modelos e rotina',
 'mensagem-de-confirmacao-de-consulta-odontologica',
 'Modelos de mensagem para confirmar consulta odontológica por tipo de atendimento e como organizar a rotina de confirmação na recepção do consultório.',
 '<p>No consultório odontológico, a confirmação muda conforme o tipo de atendimento: avaliação, procedimento longo, retorno ou manutenção de aparelho. Abaixo, modelos e uma rotina simples para a recepção.</p><h2>Modelo para avaliação</h2><p>Olá, [nome]! Sua avaliação com [dentista] está marcada para [dia] às [hora], na [clínica]. Podemos confirmar? Responda SIM ou NÃO.</p><h2>Modelo para procedimento</h2><p>Oi, [nome]! Seu procedimento com [dentista] é [dia] às [hora]. Reserve cerca de [duração]. Confirma a presença?</p><h2>Modelo para retorno</h2><p>Olá, [nome]! Passando para confirmar seu retorno em [dia], às [hora]. Se precisar remarcar, responda esta mensagem.</p><h2>Modelo para manutenção de aparelho</h2><p>Oi, [nome]! Sua manutenção do aparelho está agendada para [dia] às [hora]. Podemos confirmar?</p><h2>Rotina de confirmação na recepção</h2><ul><li>Confirme com 48 horas de antecedência para procedimentos longos e 24 horas para avaliações e retornos.</li><li>Marque na agenda quem confirmou, quem recusou e quem não respondeu.</li><li>Para os que não responderam, faça um segundo contato no dia anterior.</li><li>Tenha uma lista de espera para preencher cancelamentos de última hora.</li></ul><h2>Automatizando a rotina</h2><p>O <a href="https://utecnologia.com.br/confirmacao-de-consulta-por-whatsapp">recurso de confirmação por WhatsApp</a> da UTecnologia Saúde envia a mensagem no agendamento e o lembrete automático depois, com botões de confirmar e cancelar que atualizam a agenda. Veja o <a href="https://utecnologia.com.br/sistema-para-dentistas">sistema para dentistas</a> e os <a href="https://utecnologia.com.br/blog/modelo-de-mensagem-de-confirmacao-de-consulta-whatsapp">modelos gerais de mensagem</a>. <a href="https://utecnologia.com.br/experimentar">Teste grátis por 30 dias</a>.</p>',
 'Mensagem de confirmação de consulta odontológica: modelos e rotina',
 'Modelos de mensagem para confirmar consulta odontológica por tipo de atendimento e como organizar a rotina de confirmação na recepção.',
 'UTecnologia Saúde', 6, 1, '2026-08-31 10:00:00', '2026-08-31 10:00:00');
